# Generated by Django 3.2 on 2021-05-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20210501_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.URLField(default='https://www.denofgeek.com/wp-content/uploads/2015/02/potter.jpeg?fit=300%2C225'),
        ),
    ]
