# Generated by Django 3.2 on 2021-04-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=100)),
                ('num_of_questions', models.IntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=10)),
                ('time_limit', models.IntegerField(default=10)),
                ('maximum_marks', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
        ),
    ]
