# Generated by Django 3.1.7 on 2021-04-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210420_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='url',
            field=models.URLField(default='https://adoring-hawking-6d5afd.netlify.app/'),
        ),
    ]
