# Generated by Django 3.2 on 2021-05-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210501_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='url',
            field=models.URLField(default='https://adoring-hawking-6d5afd.netlify.app/', max_length=210),
        ),
    ]
