# Generated by Django 3.2 on 2021-04-21 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('tutorial_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(max_length=254, null=True, upload_to='uploads')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.feature')),
            ],
        ),
    ]
