# Generated by Django 3.2 on 2021-04-21 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorials',
            options={'verbose_name': 'Tutorials'},
        ),
    ]
