# Generated by Django 3.2 on 2021-04-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_alter_tutorials_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='file',
            field=models.FileField(max_length=254, null=True, upload_to='tutorials/uploads'),
        ),
    ]
