# Generated by Django 3.2 on 2021-04-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_alter_tutorials_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorials',
            name='file',
        ),
        migrations.AddField(
            model_name='tutorials',
            name='url',
            field=models.URLField(default='https://www.youtube.com/watch?v=OmKbGOARXao'),
        ),
    ]
